controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

wheel_controller:
  ros__parameters:
    left_wheel_names: [front_left_wheel_joint, back_left_wheel_joint]
    right_wheel_names: [front_right_wheel_joint, back_right_wheel_joint]
    cmd_vel_timeout: 0.25
    enable_odom_tf: false
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 4.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.5028156676260793
        has_acceleration_limits: true
        max_acceleration: 10.011262670504317
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.01, 0.01, 0.05, 0.0, 0.0, 0.015]
    publish_rate: 100.0
    wheel_radius_multiplier: 1.0
    wheel_radius: 0.0825
    wheel_separation_multiplier: 2.0
    wheel_separation: 0.39955
