firo:
    wheels_left:
      hardware_interface:
        joints:
          - front_left_wheel_joint
          - back_left_wheel_joint
    wheels_right:
      hardware_interface:
        joints:
          - front_right_wheel_joint
          - back_right_wheel_joint
    controller:
      wheels_left_state:
        type: joint_state_controller/JointStateController
        publish_rate: 100
        joints:
          - front_left_wheel_joint
          - back_left_wheel_joint
      wheels_right_state:
        type: joint_state_controller/JointStateController
        publish_rate: 100
        joints:
          - front_right_wheel_joint
          - back_right_wheel_joint
      wheels:
        type: "diff_drive_controller/DiffDriveController"
        left_wheel  : 
          - 'front_left_wheel_joint'
          - 'back_left_wheel_joint'
        right_wheel : 
          - 'front_right_wheel_joint'
          - 'back_right_wheel_joint'
        publish_rate: 100
        pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        twist_covariance_diagonal: [0.01, 0.01, 0.05, 0.0, 0.0, 0.015]
        wheel_separation: 0.39955
        wheel_separation_multiplier: 2
        wheel_radius: 0.0825
        wheel_radius_multiplier: 1
        cmd_vel_timeout: 1.0
        linear:
          x:
            has_velocity_limits: true
            max_velocity: 1.0
            has_acceleration_limits: true
            max_acceleration: 4.0
        angular:
          z:
            has_velocity_limits: true
            max_velocity: 2.5028156676260793
            has_acceleration_limits: true
            max_acceleration: 10.011262670504317
        enable_odom_tf: false