<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="firo">

  <!-- User arguments -->
  <xacro:arg name="calibration_path" default=""/>
  <xacro:arg name="imu_frequency" default="200.0"/>
  <xacro:arg name="stereo_fps" default="30"/>
  <xacro:arg name="gazebo" default="False"/>

  <!-- Parse arguments -->
  <xacro:property name="calibration_path" value="$(arg calibration_path)" />
  <xacro:if value="${calibration_path != ''}">
    <xacro:property name="calibration" value="${xacro.load_yaml(calibration_path)}" />
  </xacro:if>
  <xacro:property name="imu_frequency" value="$(arg imu_frequency)" />
  <xacro:property name="stereo_fps" value="$(arg stereo_fps)" />

  <!-- Load model parameters -->
  <xacro:property name="mechanical" value="${xacro.load_yaml('$(find firo_description)/config/mechanical.yaml')}" />

  <!-- Load materials -->
  <xacro:include filename="$(find firo_description)/urdf/materials.urdf.xacro" />

  <!-- Load subcomponents xacro -->
  <xacro:include filename="$(find firo_description)/urdf/torso.urdf.xacro" />
  <xacro:include filename="$(find firo_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find firo_description)/urdf/oak-d-w/oak-d-w.urdf.xacro" />

  <!-- Macro to simplify joint definition -->
  <xacro:macro name="joint" params="type:='fixed' parent:='base_link' child:='' xyz:='0 0 0' rpy:='0 0 0' axis:='0 0 1' limit_effort:='0.0' limit_velocity:='0.0'">
    <joint name="${child}_joint" type="${type}">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="${axis}"/>
      <xacro:if value="${type != 'fixed'}">
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
      </xacro:if>
    </joint>
  </xacro:macro>

  <link name="base_link" />
  <xacro:torso material="silver"/>
  <xacro:wheel material="white" prefix="back_left" reflect="true" />
  <xacro:wheel material="white" prefix="back_right" reflect="false" />
  <xacro:wheel material="white" prefix="front_left" reflect="true" />
  <xacro:wheel material="white" prefix="front_right" reflect="false" />
  <xacro:oak-d-w prefix="front"/>

  <xacro:joint child="torso" xyz="0 0 ${mechanical.wheel_radius}"/>
  <xacro:joint child="front_right_wheel" xyz="${mechanical.wheel_base/2} ${-mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="front_left_wheel" xyz="${mechanical.wheel_base/2} ${mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="back_right_wheel" xyz="${-mechanical.wheel_base/2} ${-mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="back_left_wheel" xyz="${-mechanical.wheel_base/2} ${mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint parent="torso" child="front_camera" xyz="0.3001 0 0.12845"/>

  <xacro:if value="$(arg gazebo)">
    <ros2_control name="GazeboSimSystem" type="system">
      <hardware>
        <plugin>gz_ros2_control/GazeboSimSystem</plugin>
      </hardware>
      <joint name="front_right_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-7.5</param>
          <param name="max">7.5</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="front_left_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-7.5</param>
          <param name="max">7.5</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="back_right_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-7.5</param>
          <param name="max">7.5</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="back_left_wheel_joint">
        <command_interface name="velocity">
          <param name="min">-7.5</param>
          <param name="max">7.5</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
    </ros2_control>
  </xacro:if>

  <xacro:unless value="$(arg gazebo)">
    <ros2_control name="odrive_can" type="actuator">
      <hardware>
        <plugin>odrive_can_driver/OdriveHardwareInterface</plugin>
        <param name="interface">can0</param>
      </hardware>
      <joint name="front_right_wheel_joint">
        <param name="node_id">10</param>
        <param name="transmission">56.25</param>
        <command_interface name="velocity" />
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="back_right_wheel_joint">
        <param name="node_id">11</param>
        <param name="transmission">56.25</param>
        <command_interface name="velocity" />
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="back_left_wheel_joint">
        <param name="node_id">12</param>
        <param name="transmission">-56.25</param>
        <command_interface name="velocity" />
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
      <joint name="front_left_wheel_joint">
        <param name="node_id">13</param>
        <param name="transmission">-56.25</param>
        <command_interface name="velocity" />
        <state_interface name="position" />
        <state_interface name="velocity" />
        <state_interface name="effort"/>
      </joint>
    </ros2_control>
  </xacro:unless>

  <gazebo>
    <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <hold_joints>true</hold_joints>
      <parameters>$(find firo_control)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>
</robot>
