<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="firo">

  <!-- User arguments -->
  <xacro:arg name="calibration_path" default=""/>
  <xacro:arg name="imu_frequency" default="200.0"/>
  <xacro:arg name="stereo_fps" default="30"/>
  
  <!-- Parse arguments -->
  <xacro:property name="calibration_path" value="$(arg calibration_path)" /> 
  <xacro:if value="${calibration_path != ''}">
    <xacro:property name="calibration" value="${xacro.load_yaml(calibration_path)}" /> 
  </xacro:if>
  <xacro:property name="imu_frequency" value="$(arg imu_frequency)" />  
  <xacro:property name="stereo_fps" value="$(arg stereo_fps)" /> 

  <!-- Load model parameters -->
  <xacro:property name="mechanical" value="${xacro.load_yaml('$(find firo_description)/config/mechanical.yaml')}" /> 
  
  <!-- Load materials -->
  <xacro:include filename="$(find firo_description)/urdf/materials.urdf.xacro" />
  
  <!-- Load subcomponents xacro -->
  <xacro:include filename="$(find firo_description)/urdf/torso.urdf.xacro" />
  <xacro:include filename="$(find firo_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find firo_description)/urdf/oak-d-w/oak-d-w.urdf.xacro" />

 <!-- Macro to simplify joint definition -->
  <xacro:macro name="joint" params="type:='fixed' parent:='base_link' child:='' xyz:='0 0 0' rpy:='0 0 0' axis:='0 0 1' limit_effort:='0.0' limit_velocity:='0.0'">
    <joint name="${child}_joint" type="${type}">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="${axis}"/>
      <xacro:if value="${type != 'fixed'}">
        <limit effort="${limit_effort}" velocity="${limit_velocity}"/>
      </xacro:if>
    </joint>
  </xacro:macro>
 
  <link name="base_link" />
  <xacro:torso material="silver"/>
  <xacro:wheel material="white" prefix="back_left" reflect="true" />
  <xacro:wheel material="white" prefix="back_right" reflect="false" />
  <xacro:wheel material="white" prefix="front_left" reflect="true" />
  <xacro:wheel material="white" prefix="front_right" reflect="false" />
  <xacro:oak-d-w prefix="front"/>
  
  <xacro:joint child="torso" xyz="0 0 ${mechanical.wheel_radius}"/>
  <xacro:joint child="front_right_wheel" xyz="${mechanical.wheel_base/2} ${-mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="front_left_wheel" xyz="${mechanical.wheel_base/2} ${mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="back_right_wheel" xyz="${-mechanical.wheel_base/2} ${-mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint child="back_left_wheel" xyz="${-mechanical.wheel_base/2} ${mechanical.wheel_track/2} ${mechanical.wheel_radius}" type="continuous" axis="0 1 0" limit_effort="7.5" limit_velocity="7.5"/>
  <xacro:joint parent="torso" child="front_camera" xyz="0.3001 0 0.12845"/>

  <transmission name="front_right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="front_right_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="front_right_wheel_joint">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <transmission name="front_left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="front_left_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="front_left_wheel_joint">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <transmission name="back_right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="back_right_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="back_right_wheel_joint">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>
  <transmission name="back_left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="back_left_wheel_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="back_left_wheel_joint">
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
    <plugin name="p3d_plugin" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>ground_truth</topicName>
      <frameName>map</frameName>
    </plugin>
  </gazebo>
</robot>
